import { Inter } from "next/font/google";
import { Rubik } from "next/font/google";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter"
});

const rubik = Rubik({
  subsets: ["latin"],
  variable: "--font-rubik"
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${rubik.variable}`}>{children}</body>
    </html>
  );
}
